collections:
  - name: "home"
    label: "Hem"
    files:
      - file: "content/home.yaml"
        label: "Hem (innehåll)"
        name: "home"
        fields:
          - { label: "Huvudrubrik", name: "main_title", widget: "string" }
          - { label: "Tagline",     name: "hero.tagline", widget: "string" }
          - { label: "Underrubrik", name: "hero.subtitle", widget: "text" }
          - label: "Statistik"
            name: "stats"
            widget: "object"
            fields:
              - { label: "Våra Lag-etikett",   name: "teams_label",     widget: "string" }
              - { label: "Senaste Nytt-etikett", name: "latest_news_label", widget: "string" }
              - { label: "Totalt Lag",         name: "total_teams",     widget: "number" }
              - { label: "A-lag",              name: "a_teams",         widget: "number" }
              - { label: "Ungdomslag",         name: "youth_teams",     widget: "number" }
              - { label: "Historia-etikett",   name: "history_years_label", widget: "string" }
              - { label: "År av Historia",     name: "history_years",   widget: "number" }
          - label: "Kommande Matcher"
            name: "upcoming"
            widget: "object"
            fields:
              - { label: "Rubrik",     name: "title", widget: "string" }
              - { label: "Underrubrik", name: "subtitle", widget: "text" }
              - { label: "Knapp-text", name: "button", widget: "string" }
          - label: "Om oss"
            name: "about"
            widget: "object"
            fields:
              - { label: "Rubrik", name: "title", widget: "string" }
              - { label: "Text",   name: "text",  widget: "text" }
          - { label: "Vision", name: "vision", widget: "text" }
          - label: "Kärnvärden"
            name: "features"
            widget: "list"
            fields:
              - { label: "Titel",       name: "title",       widget: "string" }
              - { label: "Beskrivning", name: "description", widget: "text" }
          - label: "Call-to-action (CTA)"
            name: "ctas"
            widget: "object"
            fields:
              - { label: "Visa Lag-knapp",   name: "view_teams", widget: "string" }
              - { label: "Kontakta Oss-knapp", name: "contact_us", widget: "string" }
          - label: "Footer-team"
            name: "footer_team_summary"
            widget: "object"
            fields:
              - { label: "Rubrik",   name: "title",    widget: "string" }
              - { label: "Underrubrik", name: "subtitle", widget: "string" }
          - label: "Partners-sektion"
            name: "partners_section"
            widget: "object"
            fields:
              - { label: "Rubrik", name: "title", widget: "string" }
              - { label: "Intro-text", name: "intro", widget: "text" }
              - label: "Partners per nivå"
                name: "tiers"
                widget: "list"
                fields:
                  - { label: "Nivå-etikett", name: "label", widget: "string" }
                  - label: "Företag"
                    name: "partners"
                    widget: "list"
                    fields:
                      - { label: "Namn", name: "name", widget: "string" }
